import { Inter } from "next/font/google";
import "./globals.css";
import CopyRight from "./_Components/CopyRight";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ASR GYM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <CopyRight />
      </body>
    </html>
  );
}
